### ISSUE TITLE
Scroll error

### ISSUE THREAD

**Issue by MATHAN4023** [ManikandanS8377/TempoIoT#15]
If the user scrolls the page, only the data should scroll.
![image](https://github.com/ManikandanS8377/TempoIoT/assets/116017480/eb88f1f7-929b-4c57-8bce-b86800381569)

**Comment by Nithesh005** [comment]
<img width="921" alt="image" src="https://github.com/ManikandanS8377/TempoIoT/assets/76184804/3429aa44-3547-4d06-916a-4d8faafc913c">
