### ISSUE TITLE
site details_missing field 

### ISSUE THREAD

**Issue by MATHAN4023** [ManikandanS8377/TempoIoT#17]
last update by and late update on fields are missing In the Site detail's pop page.
![image](https://github.com/ManikandanS8377/TempoIoT/assets/116017480/90639a1a-1054-4043-9fc5-908b3590fe49)

**Comment by ManikandanS8377** [comment]
1. Remove the Edit Option(Details) value's input design
2. All the values alignment should be equivalent
3. Font size and styles should globally unique
