### ISSUE TITLE
Device management filters

### ISSUE THREAD

**Issue by Nithesh005** [ManikandanS8377/TempoIoT#29]
Filters are not working properly 
<img width="878" alt="image" src="https://github.com/ManikandanS8377/TempoIoT/assets/76184804/26e3f764-40f6-49d3-901e-4e6ad9862461">

**Comment by ManikandanS8377** [comment]
Requirenment:
1. Click event should be apply while click anywhere in the drop-down options
2.  Data should be filtered based on the drop-down check boxs(multiple values)
